name: evenizer
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splash_screen_view: ^3.0.0
  url_launcher: ^6.0.15
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  cached_network_image: ^3.1.0+1
  connectivity_plus: ^2.0.3
  flutter_typeahead: ^3.2.4
  shared_preferences: ^2.0.12
  image_cropper: ^1.4.1
  provider: ^5.0.0
  shimmer: ^2.0.0
  flutter_riverpod: ^0.14.0+3
  carousel_slider: ^4.0.0
  curved_navigation_bar: ^1.0.1
  flutter_local_notifications: ^9.0.3
  percent_indicator: ^3.4.0
  photo_view: ^0.13.0
  firebase_storage: ^10.1.0
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  flutter_map: ^0.14.0
  google_sign_in: ^5.0.3
  qr_flutter: ^4.0.0
  encrypt: ^5.0.1
  sendgrid_mailer: ^0.1.3
  http: ^0.13.4
  file_picker: ^4.4.0
  flutter_pdfview: ^1.2.2
  path_provider: ^2.0.9
  multi_select_flutter: ^4.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_messaging: ^11.2.7

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  cloud_firestore_platform_interface: 5.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/audience.jpg
    - assets/images/schedule-event.png
    - assets/images/calendar.png
    - assets/images/sofa.png
    - assets/images/logo.jpg
    - assets/images/google-logo.png
    - assets/images/email.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
